version: '3.8'

services:
  garrysmod-server:
    image: lscr.io/linuxserver/garrysmod:latest
    container_name: garrysmod-server
    restart: unless-stopped
    ports:
      - "27018:27018/tcp"
      - "27018:27018/udp"
      - "27008:27008/udp"
    environment:
      - PUID=1000
      - PGID=1000
      - PORT=27018
      - MAP=gm_construct
      - MAXPLAYERS=24
    volumes:
      - gmod_data:/config

volumes:
  gmod_data:
